#!/usr/bin/env sh

mdocdate=$(date "+%d %m, %Y" | sed '
s/ 01/ Janurary/
s/ 02/ February/
s/ 03/ March/
s/ 04/ April/
s/ 05/ May/
s/ 06/ June/
s/ 07/ July/
s/ 08/ August/
s/ 09/ September/
s/ 10/ October/
s/ 11/ November/
s/ 12/ December/
')

git status --porcelain | while IFS= read -r file; do
	first="$(echo "$file" | cut -c 1)"
	case "$first" in
	' '|D)
		continue
		;;
	*)
		file="$(echo "$file" | awk '{ print $2 }')"
		case "${file##*.}" in
		[1-7]go)
			sed -i '/^\.TH/s/"[0-9]* [A-Z][a-z]*, [0-9]*"/"'"$mdocdate"'"/' "$file"
			git add "$file"
			;;
		esac
		;;
	esac
done
exit 0
